version: "3.7"
services:
  test_db_conn_postgres:
    image: test_db_conn_postgres
    container_name: test_db_conn_postgres
    build: .
    command:
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
    - DB_NAME=Test_DB1
    - DB_USER=postgres
    - DB_PASS=postgres
    - DB_HOST=postgres_db
    depends_on:
    - postgres_db

  postgres_db:
    image: postgres
    environment:
      - POSTGRES_DB=Test_DB1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5431:5431"